// !!! IMPLEMENT_ME SDL_AddTimer
// !!! IMPLEMENT_ME SDL_AllocRW
// !!! IMPLEMENT_ME SDL_AudioDriverName
// !!! IMPLEMENT_ME SDL_AudioInit
// !!! IMPLEMENT_ME SDL_AudioQuit
// !!! IMPLEMENT_ME SDL_BuildAudioCVT
// !!! IMPLEMENT_ME SDL_CDClose
// !!! IMPLEMENT_ME SDL_CDEject
// !!! IMPLEMENT_ME SDL_CDName
// !!! IMPLEMENT_ME SDL_CDNumDrives
// !!! IMPLEMENT_ME SDL_CDOpen
// !!! IMPLEMENT_ME SDL_CDPause
// !!! IMPLEMENT_ME SDL_CDPlay
// !!! IMPLEMENT_ME SDL_CDPlayTracks
// !!! IMPLEMENT_ME SDL_CDResume
// !!! IMPLEMENT_ME SDL_CDStatus
// !!! IMPLEMENT_ME SDL_CDStop
// !!! IMPLEMENT_ME SDL_ClearError
// !!! IMPLEMENT_ME SDL_CloseAudio
// !!! IMPLEMENT_ME SDL_CondBroadcast
// !!! IMPLEMENT_ME SDL_CondSignal
// !!! IMPLEMENT_ME SDL_CondWait
// !!! IMPLEMENT_ME SDL_CondWaitTimeout
// !!! IMPLEMENT_ME SDL_ConvertAudio
// !!! IMPLEMENT_ME SDL_ConvertSurface
// !!! IMPLEMENT_ME SDL_CreateCond
// !!! IMPLEMENT_ME SDL_CreateCursor
// !!! IMPLEMENT_ME SDL_CreateMutex
// !!! IMPLEMENT_ME SDL_CreateRGBSurface
// !!! IMPLEMENT_ME SDL_CreateRGBSurfaceFrom
// !!! IMPLEMENT_ME SDL_CreateSemaphore
// !!! IMPLEMENT_ME SDL_CreateThread
// !!! IMPLEMENT_ME SDL_CreateYUVOverlay
// !!! IMPLEMENT_ME SDL_Delay
// !!! IMPLEMENT_ME SDL_DestroyCond
// !!! IMPLEMENT_ME SDL_DestroyMutex
// !!! IMPLEMENT_ME SDL_DestroySemaphore
// !!! IMPLEMENT_ME SDL_DisplayFormat
// !!! IMPLEMENT_ME SDL_DisplayFormatAlpha
// !!! IMPLEMENT_ME SDL_DisplayYUVOverlay
// !!! IMPLEMENT_ME SDL_EnableKeyRepeat
// !!! IMPLEMENT_ME SDL_EnableUNICODE
// !!! IMPLEMENT_ME SDL_Error
// !!! IMPLEMENT_ME SDL_EventState
// !!! IMPLEMENT_ME SDL_FillRect
// !!! IMPLEMENT_ME SDL_Flip
// !!! IMPLEMENT_ME SDL_FreeCursor
// !!! IMPLEMENT_ME SDL_FreeRW
// !!! IMPLEMENT_ME SDL_FreeSurface
// !!! IMPLEMENT_ME SDL_FreeWAV
// !!! IMPLEMENT_ME SDL_FreeYUVOverlay
// !!! IMPLEMENT_ME SDL_GL_GetAttribute
// !!! IMPLEMENT_ME SDL_GL_GetProcAddress
// !!! IMPLEMENT_ME SDL_GL_LoadLibrary
// !!! IMPLEMENT_ME SDL_GL_Lock
// !!! IMPLEMENT_ME SDL_GL_SetAttribute
// !!! IMPLEMENT_ME SDL_GL_SwapBuffers
// !!! IMPLEMENT_ME SDL_GL_Unlock
// !!! IMPLEMENT_ME SDL_GL_UpdateRects
// !!! IMPLEMENT_ME SDL_GetAppState
// !!! IMPLEMENT_ME SDL_GetAudioStatus
// !!! IMPLEMENT_ME SDL_GetClipRect
// !!! IMPLEMENT_ME SDL_GetCursor
// !!! IMPLEMENT_ME SDL_GetError
// !!! IMPLEMENT_ME SDL_GetEventFilter
// !!! IMPLEMENT_ME SDL_GetGammaRamp
// !!! IMPLEMENT_ME SDL_GetKeyName
// !!! IMPLEMENT_ME SDL_GetKeyRepeat
// !!! IMPLEMENT_ME SDL_GetKeyState
// !!! IMPLEMENT_ME SDL_GetModState
// !!! IMPLEMENT_ME SDL_GetMouseState
// !!! IMPLEMENT_ME SDL_GetRGB
// !!! IMPLEMENT_ME SDL_GetRGBA
// !!! IMPLEMENT_ME SDL_GetRelativeMouseState
// !!! IMPLEMENT_ME SDL_GetThreadID
// !!! IMPLEMENT_ME SDL_GetTicks
// !!! IMPLEMENT_ME SDL_GetVideoInfo
// !!! IMPLEMENT_ME SDL_GetVideoSurface
// !!! IMPLEMENT_ME SDL_GetWMInfo
// !!! IMPLEMENT_ME SDL_Has3DNow
// !!! IMPLEMENT_ME SDL_Has3DNowExt
// !!! IMPLEMENT_ME SDL_HasAltiVec
// !!! IMPLEMENT_ME SDL_HasMMX
// !!! IMPLEMENT_ME SDL_HasMMXExt
// !!! IMPLEMENT_ME SDL_HasRDTSC
// !!! IMPLEMENT_ME SDL_HasSSE
// !!! IMPLEMENT_ME SDL_HasSSE2
// !!! IMPLEMENT_ME SDL_Init
// !!! IMPLEMENT_ME SDL_InitSubSystem
// !!! IMPLEMENT_ME SDL_JoystickClose
// !!! IMPLEMENT_ME SDL_JoystickEventState
// !!! IMPLEMENT_ME SDL_JoystickGetAxis
// !!! IMPLEMENT_ME SDL_JoystickGetBall
// !!! IMPLEMENT_ME SDL_JoystickGetButton
// !!! IMPLEMENT_ME SDL_JoystickGetHat
// !!! IMPLEMENT_ME SDL_JoystickIndex
// !!! IMPLEMENT_ME SDL_JoystickName
// !!! IMPLEMENT_ME SDL_JoystickNumAxes
// !!! IMPLEMENT_ME SDL_JoystickNumBalls
// !!! IMPLEMENT_ME SDL_JoystickNumButtons
// !!! IMPLEMENT_ME SDL_JoystickNumHats
// !!! IMPLEMENT_ME SDL_JoystickOpen
// !!! IMPLEMENT_ME SDL_JoystickOpened
// !!! IMPLEMENT_ME SDL_JoystickUpdate
// !!! IMPLEMENT_ME SDL_KillThread
// !!! IMPLEMENT_ME SDL_Linked_Version
// !!! IMPLEMENT_ME SDL_ListModes
// !!! IMPLEMENT_ME SDL_LoadBMP_RW
// !!! IMPLEMENT_ME SDL_LoadFunction
// !!! IMPLEMENT_ME SDL_LoadObject
// !!! IMPLEMENT_ME SDL_LoadWAV_RW
// !!! IMPLEMENT_ME SDL_LockAudio
// !!! IMPLEMENT_ME SDL_LockSurface
// !!! IMPLEMENT_ME SDL_LockYUVOverlay
// !!! IMPLEMENT_ME SDL_LowerBlit
// !!! IMPLEMENT_ME SDL_MapRGB
// !!! IMPLEMENT_ME SDL_MapRGBA
// !!! IMPLEMENT_ME SDL_MixAudio
// !!! IMPLEMENT_ME SDL_NumJoysticks
// !!! IMPLEMENT_ME SDL_OpenAudio
// !!! IMPLEMENT_ME SDL_PauseAudio
// !!! IMPLEMENT_ME SDL_PeepEvents
// !!! IMPLEMENT_ME SDL_PollEvent
// !!! IMPLEMENT_ME SDL_PumpEvents
// !!! IMPLEMENT_ME SDL_PushEvent
// !!! IMPLEMENT_ME SDL_Quit
// !!! IMPLEMENT_ME SDL_QuitSubSystem
// !!! IMPLEMENT_ME SDL_RWFromConstMem
// !!! IMPLEMENT_ME SDL_RWFromFP
// !!! IMPLEMENT_ME SDL_RWFromFile
// !!! IMPLEMENT_ME SDL_RWFromMem
// !!! IMPLEMENT_ME SDL_ReadBE16
// !!! IMPLEMENT_ME SDL_ReadBE32
// !!! IMPLEMENT_ME SDL_ReadBE64
// !!! IMPLEMENT_ME SDL_ReadLE16
// !!! IMPLEMENT_ME SDL_ReadLE32
// !!! IMPLEMENT_ME SDL_ReadLE64
// !!! IMPLEMENT_ME SDL_RemoveTimer
// !!! IMPLEMENT_ME SDL_SaveBMP_RW
// !!! IMPLEMENT_ME SDL_SemPost
// !!! IMPLEMENT_ME SDL_SemTryWait
// !!! IMPLEMENT_ME SDL_SemValue
// !!! IMPLEMENT_ME SDL_SemWait
// !!! IMPLEMENT_ME SDL_SemWaitTimeout
// !!! IMPLEMENT_ME SDL_SetAlpha
// !!! IMPLEMENT_ME SDL_SetClipRect
// !!! IMPLEMENT_ME SDL_SetColorKey
// !!! IMPLEMENT_ME SDL_SetColors
// !!! IMPLEMENT_ME SDL_SetCursor
// !!! IMPLEMENT_ME SDL_SetError
// !!! IMPLEMENT_ME SDL_SetEventFilter
// !!! IMPLEMENT_ME SDL_SetGamma
// !!! IMPLEMENT_ME SDL_SetGammaRamp
// !!! IMPLEMENT_ME SDL_SetModState
// !!! IMPLEMENT_ME SDL_SetPalette
// !!! IMPLEMENT_ME SDL_SetTimer
// !!! IMPLEMENT_ME SDL_SetVideoMode
// !!! IMPLEMENT_ME SDL_ShowCursor
// !!! IMPLEMENT_ME SDL_SoftStretch
// !!! IMPLEMENT_ME SDL_ThreadID
// !!! IMPLEMENT_ME SDL_UnloadObject
// !!! IMPLEMENT_ME SDL_UnlockAudio
// !!! IMPLEMENT_ME SDL_UnlockSurface
// !!! IMPLEMENT_ME SDL_UnlockYUVOverlay
// !!! IMPLEMENT_ME SDL_UpdateRect
// !!! IMPLEMENT_ME SDL_UpdateRects
// !!! IMPLEMENT_ME SDL_UpperBlit
// !!! IMPLEMENT_ME SDL_VideoDriverName
// !!! IMPLEMENT_ME SDL_VideoInit
// !!! IMPLEMENT_ME SDL_VideoModeOK
// !!! IMPLEMENT_ME SDL_VideoQuit
// !!! IMPLEMENT_ME SDL_WM_GetCaption
// !!! IMPLEMENT_ME SDL_WM_GrabInput
// !!! IMPLEMENT_ME SDL_WM_IconifyWindow
// !!! IMPLEMENT_ME SDL_WM_SetCaption
// !!! IMPLEMENT_ME SDL_WM_SetIcon
// !!! IMPLEMENT_ME SDL_WM_ToggleFullScreen
// !!! IMPLEMENT_ME SDL_WaitEvent
// !!! IMPLEMENT_ME SDL_WaitThread
// !!! IMPLEMENT_ME SDL_WarpMouse
// !!! IMPLEMENT_ME SDL_WasInit
// !!! IMPLEMENT_ME SDL_WriteBE16
// !!! IMPLEMENT_ME SDL_WriteBE32
// !!! IMPLEMENT_ME SDL_WriteBE64
// !!! IMPLEMENT_ME SDL_WriteLE16
// !!! IMPLEMENT_ME SDL_WriteLE32
// !!! IMPLEMENT_ME SDL_WriteLE64
// !!! IMPLEMENT_ME SDL_iconv
// !!! IMPLEMENT_ME SDL_iconv_string
// !!! IMPLEMENT_ME SDL_lltoa
// !!! IMPLEMENT_ME SDL_ltoa
// !!! IMPLEMENT_ME SDL_mutexP
// !!! IMPLEMENT_ME SDL_mutexV
// !!! IMPLEMENT_ME SDL_revcpy
// !!! IMPLEMENT_ME SDL_strlcat
// !!! IMPLEMENT_ME SDL_strlcpy
// !!! IMPLEMENT_ME SDL_strlwr
// !!! IMPLEMENT_ME SDL_strrev
// !!! IMPLEMENT_ME SDL_strupr
// !!! IMPLEMENT_ME SDL_ulltoa
// !!! IMPLEMENT_ME SDL_ultoa
// !!! IMPLEMENT_ME X11_KeyToUnicode
